server:
  port: 8099

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5739/testdb
    username: demo
    password: demo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
#          use_jdbc_metadata_defaults: true
#        jdbc:
#          lob:
#            non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/demo
  cache:
    type: simple
  main:
    lazy-initialization: true